config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :salutes, only: [:index, :create]

  get "/sign_up" => "users#new", as: :sign_up
  get "/sign_in" => "sessions#new", as: :sign_in
  get "/sign_out" => "sessions#destroy", as: :sign_out
  root "salutes#index"

end

app/models/salute.rb
class Salute < ActiveRecord::Base
  belongs_to :receiver, class_name: "User"
  belongs_to :sender, class_name: "User"

  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sent_salutes, foreign_key: "sender_id", class_name: "Salute"
  has_many :received_salutes, foreign_key: "receiver_id", class_name: "Salute"

  validates :username, format: { with: /\A[a-zA-z]+\z/, 
    message: "Username field only allows letters!"}, uniqueness: true
  validates :password_digest, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login
end

app/controllers/salutes_controller.rb
class SalutesController < ApplicationController
  def index
    @salute = Salute.new
    @users = User.all
    @salutes = current_user.received_salutes.order("created_at DESC")
  end

  def create
    @salute = current_user.sent_salutes.create(target_user_params)
    salute_content = render @salute
    Pusher[target_user_params[:receiver_id].to_s].trigger('new-salute', {content: salute_content})
  end

  private

  def target_user_params
  params.require(:salute).permit(:receiver_id).
  merge(body: "Salut!")
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Salutr</title>
  <script src="//js.pusher.com/2.2/pusher.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <%if signed_in?%>
  <script>
    window.CHANNEL = "<%= current_user.id%>";
    window.PUSHER = "<%= ENV.fetch('PUSHER_APP_KEY')%>";
  </script>
  <%end%>

  </head>
<body>
<h1> <%= link_to "Salut!", root_path %> </h1>
<% if signed_in?%>
  <div>You are currently signed in as <%= current_user.username%></div>
  <%= link_to "Sign out", sign_out_path %></h1>
  <% else%>
  <%= link_to "Sign up", sign_up_path %>
  <%end%>
<%= yield %>

</body>
</html>

app/views/salutes/_salute.html.erb
<li id ="salutes">
  <div>
  <%= salute.body %>
  </div>
  <div>
  <%= salute.sender.username %>
  </div>
  <div>
  <%= time_ago_in_words(salute.created_at) %> ago
  </div>
</li>

app/views/salutes/index.html.erb
<h2> Salut your friends! Here we go! </h2>

<%= form_for @salute, html: {id: "new_salute"} do |f| %>
<%= f.collection_select(:receiver_id, @users, :id, :username) %>
<%= f.submit "Salut!" %>
<% end%>

<ul>
<%= render @salutes%>
</ul> 

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>